# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Negative Binomial GLMM fit for RNA-Seq expression using MCMC (contrast version)
#'
#' Estimate Negative Binomial regressioin coefficients, dispersion parameter, and random intercept variance using MCMC with a weighted least squares proposal
#'
#' This function estimates regression parameters using an improper prior on random intercept variance (proportional to 1/sigma)
#'
#'
#'
#' @param counts A numeric matrix of RNA-Seq counts (rows are genes, columns are samples)
#' @param design_mat The fixed effects design matrix for mean response
#' @param design_mat_re The design matrix for random intercepts
#' @param contrast_mat A numeric matrix of linear contrasts of fixed effects to be tested.  Each row is considered to be an independent test, and each are done seperately
#' @param prior_sd_betas Prior std. dev. in normal prior for regression coefficients
#' @param prior_sd_betas_a Alpha parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_betas_b Beta parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_rs Prior std. dev in log-normal prior for dispersion parameters
#' @param prior_mean_log_rs Vector of prior means for log of dispersion parameters
#' @param rw_sd_rs Random walk std. dev. for proposing dispersion values (normal distribution centerd at current value)
#' @param n_it Number of iterations to run MCMC
#' @param log_offset Vector of offsets on log scale
#' @param prop_burn_in Proportion of MCMC chain to discard as burn-in when computing summaries
#' @param starting_betas Numeric matrix of starting values for the regression coefficients.  For best results, supply starting values for at least the intercept (e.g. row means of counts matrix)
#' @param num_accept Number of forced accepts of fixed and random effects at the beginning of the MCMC.  In practice forcing about 20 accepts (default value) prevents inverse errors at the start of chains and gives better mixing overall
#'
#' @author Brian Vestal
#'
#' @return
#' Returns a list with a cube of regression parameters, including random effects, a matrix of dispersion values, and a matrix of random intercept variances
#'
#' @export
NULL

#' Negative Binomial GLMM fit for RNA-Seq expression using MCMC (contrast version)
#'
#' Estimate Negative Binomial regressioin coefficients, dispersion parameter, and random intercept variance using MCMC with a weighted least squares proposal
#'
#' This function estimates regression parameters using a half-Cauchy prior on random intercept variance
#'
#'
#'
#' @param counts A numeric matrix of RNA-Seq counts (rows are genes, columns are samples)
#' @param design_mat The fixed effects design matrix for mean response
#' @param design_mat_re The design matrix for random intercepts
#' @param contrast_mat A numeric matrix of linear contrasts of fixed effects to be tested.  Each row is considered to be an independent test, and each are done seperately
#' @param prior_sd_betas Prior std. dev. in normal prior for regression coefficients
#' @param prior_sd_betas_a Alpha parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_betas_b Beta parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_rs Prior std. dev in log-normal prior for dispersion parameters
#' @param prior_mean_log_rs Vector of prior means for log of dispersion parameters
#' @param rw_sd_rs Random walk std. dev. for proposing dispersion values (normal distribution centerd at current value)
#' @param n_it Number of iterations to run MCMC
#' @param log_offset Vector of offsets on log scale
#' @param prop_burn_in Proportion of MCMC chain to discard as burn-in when computing summaries
#' @param starting_betas Numeric matrix of starting values for the regression coefficients.  For best results, supply starting values for at least the intercept (e.g. row means of counts matrix)
#' @param num_accept Number of forced accepts of fixed and random effects at the beginning of the MCMC.  In practice forcing about 20 accepts (default value) prevents inverse errors at the start of chains and gives better mixing overall
#'
#' @author Brian Vestal
#'
#' @return
#' Returns a list with a cube of regression parameters, including random effects, a matrix of dispersion values, and a matrix of random intercept variances
#'
NULL

#' Negative Binomial GLMM fit for RNA-Seq expression using MCMC (contrast version)
#'
#' Estimate Negative Binomial regressioin coefficients, dispersion parameter, and random intercept variance using MCMC with a weighted least squares proposal
#'
#' This version uses a half-Cauchy prior for both random intercept variance and NB dispersion
#'
#'
#'
#' @param counts A numeric matrix of RNA-Seq counts (rows are genes, columns are samples)
#' @param design_mat The fixed effects design matrix for mean response
#' @param design_mat_re The design matrix for random intercepts
#' @param contrast_mat A numeric matrix of linear contrasts of fixed effects to be tested.  Each row is considered to be an independent test, and each are done seperately
#' @param prior_sd_betas Prior std. dev. in normal prior for regression coefficients
#' @param prior_sd_betas_a Alpha parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_betas_b Beta parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_rs Prior std. dev in log-normal prior for dispersion parameters
#' @param prior_mean_log_rs Vector of prior means for log of dispersion parameters
#' @param rw_sd_rs Random walk std. dev. for proposing dispersion values (normal distribution centerd at current value)
#' @param n_it Number of iterations to run MCMC
#' @param log_offset Vector of offsets on log scale
#' @param prop_burn_in Proportion of MCMC chain to discard as burn-in when computing summaries
#' @param starting_betas Numeric matrix of starting values for the regression coefficients.  For best results, supply starting values for at least the intercept (e.g. row means of counts matrix)
#' @param num_accept Number of forced accepts of fixed and random effects at the beginning of the MCMC.  In practice forcing about 20 accepts (default value) prevents inverse errors at the start of chains and gives better mixing overall
#'
#' @author Brian Vestal
#'
#' @return
#' Returns a list with a cube of regression parameters, including random effects, a matrix of dispersion values, and a matrix of random intercept variances
#'
NULL

#' Negative Binomial GLMM fit for RNA-Seq expression using MCMC (contrast version)
#'
#' Estimate Negative Binomial regressioin coefficients, dispersion parameter, and random intercept variance using MCMC with a weighted least squares proposal
#'
#' This function estimates regression parameters and returns the entire chain instead of just posterior summaires
#'
#'
#'
#' @param counts A numeric matrix of RNA-Seq counts (rows are genes, columns are samples)
#' @param design_mat The fixed effects design matrix for mean response
#' @param design_mat_re The design matrix for random intercepts
#' @param contrast_mat A numeric matrix of linear contrasts of fixed effects to be tested.  Each row is considered to be an independent test, and each are done seperately
#' @param prior_sd_betas Prior std. dev. in normal prior for regression coefficients
#' @param prior_sd_betas_a Alpha parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_betas_b Beta parameter in inverse gamma prior for random intercept variance
#' @param prior_sd_rs Prior std. dev in log-normal prior for dispersion parameters
#' @param prior_mean_log_rs Vector of prior means for log of dispersion parameters
#' @param rw_sd_rs Random walk std. dev. for proposing dispersion values (normal distribution centerd at current value)
#' @param n_it Number of iterations to run MCMC
#' @param log_offset Vector of offsets on log scale
#' @param prop_burn_in Proportion of MCMC chain to discard as burn-in when computing summaries
#' @param starting_betas Numeric matrix of starting values for the regression coefficients.  For best results, supply starting values for at least the intercept (e.g. row means of counts matrix)
#' @param num_accept Number of forced accepts of fixed and random effects at the beginning of the MCMC.  In practice forcing about 20 accepts (default value) prevents inverse errors at the start of chains and gives better mixing overall
#'
#' @author Brian Vestal
#'
#' @return
#' Returns a list with a cube of regression parameters, including random effects, a matrix of dispersion values, and a matrix of random intercept variances
#'
NULL

nbglm_mcmc_rw <- function(counts, design_mat, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn = .10, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglm_mcmc_rw', PACKAGE = 'mcmseq', counts, design_mat, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_rw <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn = .10, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_rw', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn, return_cont, beta_names, cont_names)
}

nbglm_mcmc_wls <- function(counts, design_mat, contrast_mat, prior_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, burn_in_prop = .1, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglm_mcmc_wls', PACKAGE = 'mcmseq', counts, design_mat, contrast_mat, prior_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, burn_in_prop, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_wls <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in = 0.10, num_accept = 20L, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_wls', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in, num_accept, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_wls3 <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, rw_sd_sigma, log_offset, starting_betas, prop_burn_in = 0.10, tau = 10, num_accept = 20L, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_wls3', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, rw_sd_sigma, log_offset, starting_betas, prop_burn_in, tau, num_accept, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_wls4 <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, rw_sd_sigma, log_offset, starting_betas, prop_burn_in = 0.10, tau = 10, num_accept = 20L, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_wls4', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, rw_sd_sigma, log_offset, starting_betas, prop_burn_in, tau, num_accept, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_wls_wc <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in = 0.10, num_accept = 20L, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_wls_wc', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in, num_accept, return_cont, beta_names, cont_names)
}

