# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nbglm_mcmc_rw <- function(counts, design_mat, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn = .10, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglm_mcmc_rw', PACKAGE = 'mcmseq', counts, design_mat, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_rw <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn = .10, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_rw', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, rw_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn, return_cont, beta_names, cont_names)
}

nbglm_mcmc_wls <- function(counts, design_mat, contrast_mat, prior_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, burn_in_prop = .1, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglm_mcmc_wls', PACKAGE = 'mcmseq', counts, design_mat, contrast_mat, prior_sd_betas, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, burn_in_prop, return_cont, beta_names, cont_names)
}

nbglmm_mcmc_wls <- function(counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in = 0.10, num_accept = 20L, return_cont = FALSE, beta_names = NA_character_, cont_names = NA_character_) {
    .Call('_mcmseq_nbglmm_mcmc_wls', PACKAGE = 'mcmseq', counts, design_mat, design_mat_re, contrast_mat, prior_sd_betas, prior_sd_betas_a, prior_sd_betas_b, prior_sd_rs, prior_mean_log_rs, n_it, rw_sd_rs, log_offset, starting_betas, prop_burn_in, num_accept, return_cont, beta_names, cont_names)
}

